/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OnboardRouteImport } from './routes/onboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIdRouteImport } from './routes/profile.$id'
import { Route as OnboardTradeRouteImport } from './routes/onboard.trade'
import { Route as OnboardTechRouteImport } from './routes/onboard.tech'
import { Route as OnboardAgricultureRouteImport } from './routes/onboard.agriculture'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardRoute = OnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIdRoute = ProfileIdRouteImport.update({
  id: '/profile/$id',
  path: '/profile/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardTradeRoute = OnboardTradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => OnboardRoute,
} as any)
const OnboardTechRoute = OnboardTechRouteImport.update({
  id: '/tech',
  path: '/tech',
  getParentRoute: () => OnboardRoute,
} as any)
const OnboardAgricultureRoute = OnboardAgricultureRouteImport.update({
  id: '/agriculture',
  path: '/agriculture',
  getParentRoute: () => OnboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRouteWithChildren
  '/register': typeof RegisterRoute
  '/onboard/agriculture': typeof OnboardAgricultureRoute
  '/onboard/tech': typeof OnboardTechRoute
  '/onboard/trade': typeof OnboardTradeRoute
  '/profile/$id': typeof ProfileIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRouteWithChildren
  '/register': typeof RegisterRoute
  '/onboard/agriculture': typeof OnboardAgricultureRoute
  '/onboard/tech': typeof OnboardTechRoute
  '/onboard/trade': typeof OnboardTradeRoute
  '/profile/$id': typeof ProfileIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRouteWithChildren
  '/register': typeof RegisterRoute
  '/onboard/agriculture': typeof OnboardAgricultureRoute
  '/onboard/tech': typeof OnboardTechRoute
  '/onboard/trade': typeof OnboardTradeRoute
  '/profile/$id': typeof ProfileIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/onboard'
    | '/register'
    | '/onboard/agriculture'
    | '/onboard/tech'
    | '/onboard/trade'
    | '/profile/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/onboard'
    | '/register'
    | '/onboard/agriculture'
    | '/onboard/tech'
    | '/onboard/trade'
    | '/profile/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/onboard'
    | '/register'
    | '/onboard/agriculture'
    | '/onboard/tech'
    | '/onboard/trade'
    | '/profile/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  OnboardRoute: typeof OnboardRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  ProfileIdRoute: typeof ProfileIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboard': {
      id: '/onboard'
      path: '/onboard'
      fullPath: '/onboard'
      preLoaderRoute: typeof OnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$id': {
      id: '/profile/$id'
      path: '/profile/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof ProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboard/trade': {
      id: '/onboard/trade'
      path: '/trade'
      fullPath: '/onboard/trade'
      preLoaderRoute: typeof OnboardTradeRouteImport
      parentRoute: typeof OnboardRoute
    }
    '/onboard/tech': {
      id: '/onboard/tech'
      path: '/tech'
      fullPath: '/onboard/tech'
      preLoaderRoute: typeof OnboardTechRouteImport
      parentRoute: typeof OnboardRoute
    }
    '/onboard/agriculture': {
      id: '/onboard/agriculture'
      path: '/agriculture'
      fullPath: '/onboard/agriculture'
      preLoaderRoute: typeof OnboardAgricultureRouteImport
      parentRoute: typeof OnboardRoute
    }
  }
}

interface OnboardRouteChildren {
  OnboardAgricultureRoute: typeof OnboardAgricultureRoute
  OnboardTechRoute: typeof OnboardTechRoute
  OnboardTradeRoute: typeof OnboardTradeRoute
}

const OnboardRouteChildren: OnboardRouteChildren = {
  OnboardAgricultureRoute: OnboardAgricultureRoute,
  OnboardTechRoute: OnboardTechRoute,
  OnboardTradeRoute: OnboardTradeRoute,
}

const OnboardRouteWithChildren =
  OnboardRoute._addFileChildren(OnboardRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  OnboardRoute: OnboardRouteWithChildren,
  RegisterRoute: RegisterRoute,
  ProfileIdRoute: ProfileIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
